apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: ConfigMap  # for versions before 1.9.0 use ConfigMap
metadata: # metadata for ConfigMap
  name: game-demo # name of ConfigMap
data: # data contained in ConfigMap
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3" # note that the value is a string
  ui_properties_file_name: "user-interface.properties" # and another string value

  # file-like keys
  game.properties: | # note that the value is multi-line using `|`
    enemy.types=aliens,monsters 
    player.maximum-lives=5    
  user-interface.properties: | # another file-like key
    color.good=purple
    color.bad=yellow
    allow.textmode=true 