apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
    - name: SECRET_USERNAME # the name of the environment variable
      valueFrom: # defines the source of the value
        secretKeyRef: # defines the secret to select from
          name: mysecret # the name of the secret
          key: username # the key to select from
          optional: false # if true, the pod will start even if the secret is not found
    
    - name: SECRET_PASSWORD # the name of the environment variable
      valueFrom: # defines the source of the value
        secretKeyRef: # defines  the secret to select from
          name: mysecret # the name of the secret
          key: password # the key to select from
          optional: false # if true, the pod will start even if the secret is not found
  restartPolicy: Never # this is just for the example
