all:
  hosts:
    web01:
      ansible_host: 192.168.1.17
      #ansible_user: djazi
    web02:
      ansible_host: 192.168.1.17
    db01:
      ansible_host: 192.168.1.17
  children:
    webservers:
      hosts:
        web01:
        web02:
    dbservers:
      hosts:
        db01:
    dc_oregon:
      children:
        webservers:
        dbservers:
      vars:
        ansible_user: djazi