---
- name: Provisionning servers
  hosts: all
  become: yes
  tasks:
    - name: Install ntp agent on AlmaLinux 
      yum:
        name: "{{ item }}"
        state: latest
      when: ansible_distribution == "AlmaLinux"
      loop:
        - chrony
        - wget
        - vim
        - zip 
        - unzip
        - git
    - name: Install ntp agent on ubuntu
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
      loop:
        - ntp
        - wget
        - vim
        - zip 
        - unzip
        - git
        
    - name: Start ntp service on AlmaLinux
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "AlmaLinux"
    - name: Start ntp service on ubuntu
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"
    - name: banner file
      copy:
        content: This server is managed by ansible
        dest: /etc/motd

    - name: Deploy ntp agent on AlmaLinux
      template:
        src: templates/ntpconf_alma
        dest: /etc/chrony.conf
        backup: yes
      when: ansible_distribution == "AlmaLinux"
    
    - name: Deploy ntp agent on ubuntu
      template:
        src: templates/ntpconf_ubuntu
        dest: /etc/ntp.conf
        backup: yes
      when: ansible_distribution == "Ubuntu"

    - name: REStart ntp service on AlmaLinux
      service:
        name: chronyd
        state: restarted
        enabled: yes
      when: ansible_distribution == "AlmaLinux"

    - name: ReStart ntp service on ubuntu
      service:
        name: ntp
        state: restarted
        enabled: yes
      when: ansible_distribution == "Ubuntu"
      
    - name: Create a folder
      file:
        path: /opt/teest21
        state: directory
        mode: 0755
      when: ansible_distribution == "AlmaLinux"
      