---
# tasks file for post-install
- name: Install ntp agent on AlmaLinux 
  yum:
    name: "{{ item }}"
    state: latest
  when: ansible_distribution == "AlmaLinux"
  loop:
    - chrony
    - wget
    - vim
    - zip 
    - unzip
    - git
- name: Install ntp agent on ubuntu
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  loop:
    - ntp
    - wget
    - vim
    - zip 
    - unzip
    - git
    
- name: Start ntp service on AlmaLinux
  service:
    name: chronyd
    state: started
    enabled: yes
  when: ansible_distribution == "AlmaLinux"
- name: Start ntp service on ubuntu
  service:
    name: ntp
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: Banner file
  copy:
    content: This server is managed by ansible
    dest: /etc/motd

- name: Create a folder
  file:
    path: "{{dir1}}"
    state: directory
  when: ansible_distribution == "AlmaLinux"

- name: Deploy ntp agent on AlmaLinux
  template:
    src: ntpconf_alma.j2
    dest: /etc/chrony.conf
    backup: yes
  when: ansible_distribution == "AlmaLinux"
  notify:
    - REStart ntp service on AlmaLinux

- name: Deploy ntp agent on ubuntu
  template:
    src: ntpconf_ubuntu.j2
    dest: /etc/ntp.conf
    backup: yes
  when: ansible_distribution == "Ubuntu"
  notify:
    - ReStart ntp service on ubuntu
- name: Dump file
  copy:
    src: dump.txt
    dest: /tmp/myfile.txt