---
- name: Understanding vars
  hosts: all
  become: yes
  #gather_facts: False
  tasks:
  - name: create user
    ansible.builtin.user:
      name: "{{USRNM}}"
      comment: "{{COMMENT}}"
    register: userout
  - debug:
      var: userout.name
  - debug:
      var: userout.comment
        

