---
- name: DBservers setup
  hosts: dbservers
  become: yes
  vars:
  tasks:
    - debug:
        msg: "The {{dbname}} {{dbuser}} {{dbpass}}"
    - name: Install mariadb
      ansible.builtin.yum:
        name: mariadb-server
        state: present
    - name: Start mariadb service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes
    - name: Install python3 mysql
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present
    
    - name: create database
      community.mysql.mysql_db:
        name: "{{dbname}}"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: create new  database
      community.mysql.mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
      register: dbout
  
    - name: print output
      debug:
        var: dbout
  

